version: '3'
services:
  api:
    image: api
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - dockernetwork
    restart: always
    depends_on: 
      - opcua
  opcua:
    image: opcserver
    container_name: opcserver
    ports:
      - "4841:4840"
    networks:
      - dockernetwork
    restart: always
    depends_on: 
      - cassandra
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - dockernetwork
networks:
  dockernetwork:
    driver: bridge
volumes:
  cassandra_data: