version: '3'
services:
  simpleopcua:
    build:
      context: ./SimpleOPCUAServer
      dockerfile: Dockerfile
    ports:
      - 4840:4840
    networks:
      - mynetwork

  clientapi:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mynetwork

networks:
  mynetwork: