version: '3'
services:
  
  rabbitmq:
    image: rabbitmq:3.9.11-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     - ZOOKEEPER_CLIENT_PORT=2181
  #   ports:
  #     - 2181:2181

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  #   ports:
  #     - 9092:9092
      
volumes:
  rabbitmq_data: