version: '3'
services:

  opctobroker:
    container_name: opctobroker
    image: joaoribeiro5039/opctobroker:latest
    ports:
      - 5672:5672
      - 1883:1883
    environment:
      - RABBITMQ_BROKER_HOST=JR-PC #RabbitMQ 
      - RABBITMQ_BROKER_USER=admin
      - RABBITMQ_BROKER_PASSWORD=admin
      - KAFKA_BROKER_HOST=JR-PC:29092 #Kafka
      - KAFKA_PRODUCER_ID=my_producer
      - KAFKA_PRODUCER_PREFIX=server1
      - OPC_UA_HOST=opcuaserver:4840 #OPC UA 
      - MQTT_BROKER_HOST=JR-PC #Mqtt
      - MQTT_BROKER_PORT=1883 
    restart: always

  opcuaserver:
    container_name: opcuaserver
    image: joaoribeiro5039/opcuaserver:latest
    ports:
      - "4840:4840"
    restart: always
