version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.2.0
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    depends_on:
      - opcuaserver

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra

  opcuaserver:
    container_name: opcuaserver
    image: joaoribeiro5039/opcuaserver:latest
    ports:
      - "4840:4840"
    restart: always
    depends_on:
      - cassandra


  opctobroker:
    container_name: opctobroker
    image: joaoribeiro5039/opctobroker:latest
    environment:
      - RABBITMQ_BROKER_HOST=rabbitmq
      - RABBITMQ_BROKER_USER=admin
      - RABBITMQ_BROKER_PASSWORD=admin
      - RABBITMQ_BROKER_QUEUE_PREFIX=server1
      - OPC_UA_HOST=opcuaserver:4840
      - KAFKA_BROKER_HOST=kafka:29092
      - KAFKA_PRODUCER_ID=my_producer
      - KAFKA_PRODUCER_PREFIX=Server1
      - OPC_UA_HOST=opcuaserver:4840
    restart: always
    depends_on:
      - rabbitmq

  rabbitmqtocassandra:
    container_name: rabbitmqtocassandra
    image: joaoribeiro5039/rabbitmqtocassandra:latest
    environment:
      - RABBITMQ_BROKER_HOST=rabbitmq
      - RABBITMQ_BROKER_QUEUE_PREFIX=server1
      - RABBITMQ_BROKER_USER=admin
      - RABBITMQ_BROKER_PASSWORD=admin
      - CASSANDRA_DB_HOST=cassandra
      - CASSANDRA_DB_TABLENAME=Server1
    restart: unless-stopped
    depends_on:
      - opctorabbitmq
volumes:
  rabbitmq_data:
  cassandra-data: