name: Checks

on: [push]

jobs:

  test-docker-compose-with-build:
    name: Test Docker compose up with source code
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose-build.yml"
  
  publish-simpleopcua:
    needs: test-docker-compose-with-build
    name: Publish simpleopcua to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image simpleopcua
        working-directory: ./opcservers
        run: docker build . --file Dockerfile --tag simpleopcua:latest
        
      - name: Build Latest simpleopcua Docker image
        working-directory: ./opcservers
        run: docker tag simpleopcua:latest joaoribeiro5039/simpleopcua:latest

      - name: Docker Push Latest simpleopcua
        run: docker push joaoribeiro5039/simpleopcua:latest
  
  publish-dataprocess:
    needs: publish-simpleopcua
    name: Publish dataprocess to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image simpleopcua
        working-directory: ./dataprocess
        run: docker build . --file Dockerfile --tag dataprocess:latest
        
      - name: Build Latest simpleopcua Docker image
        working-directory: ./dataprocess
        run: docker tag dataprocess:latest joaoribeiro5039/dataprocess:latest

      - name: Docker Push Latest simpleopcua
        run: docker push joaoribeiro5039/dataprocess:latest
        
  test-docker-compose-with-dockerhub:
    needs: publish-dataprocess
    name: Test Docker compose with Docker hub components
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose-dockerhub.yml"
              