name: Checks

on: [push]

jobs:

  test-docker-compose-with-build:
    name: Test Docker compose up with source code
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose-build.yml"
  
  publish-opcuaserver:
    needs: test-docker-compose-with-build
    name: Publish opcuaserver to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image opcuaserver
        working-directory: ./opcserver
        run: docker build . --file Dockerfile --tag opcuaserver:latest
        
      - name: Build Latest opcuaserver Docker image
        working-directory: ./opcserver
        run: docker tag opcuaserver:latest joaoribeiro5039/opcuaserver:latest

      - name: Docker Push Latest opcuaserver
        run: docker push joaoribeiro5039/opcuaserver:latest
  
  publish-opctobroker:
    needs: test-docker-compose-with-build
    name: Publish opctobroker to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image opctobroker
        working-directory: ./opctobroker
        run: docker build . --file Dockerfile --tag opctobroker:latest
        
      - name: Build Latest opctobroker Docker image
        working-directory: ./opctobroker
        run: docker tag opctobroker:latest joaoribeiro5039/opctobroker:latest

      - name: Docker Push Latest opctobroker
        run: docker push joaoribeiro5039/opctobroker:latest
  
  publish-rabbitmqtocassandra:
    needs: test-docker-compose-with-build
    name: Publish rabbitmqtocassandra to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image rabbitmqtocassandra
        working-directory: ./rabbitmqtocassandra
        run: docker build . --file Dockerfile --tag rabbitmqtocassandra:latest
        
      - name: Build Latest rabbitmqtocassandra Docker image
        working-directory: ./rabbitmqtocassandra
        run: docker tag rabbitmqtocassandra:latest joaoribeiro5039/rabbitmqtocassandra:latest

      - name: Docker Push Latest rabbitmqtocassandra
        run: docker push joaoribeiro5039/rabbitmqtocassandra:latest


  publish-opcwriter:
    needs: test-docker-compose-with-build
    name: Publish opcwriter to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image opcwriter
        working-directory: ./opcwriter
        run: docker build . --file Dockerfile --tag opcwriter:latest
        
      - name: Build Latest opcwriter Docker image
        working-directory: ./opcwriter
        run: docker tag opcwriter:latest joaoribeiro5039/opcwriter:latest

      - name: Docker Push Latest opcwriter
        run: docker push joaoribeiro5039/opcwriter:latest


  test-docker-compose-with-dockerhub:
    needs: [publish-opcwriter, publish-rabbitmqtocassandra, publish-opctobroker, publish-opcuaserver]
    name: Test Docker compose with Docker hub components
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose-dockerhub.yml"
              