name: Checks

on: [push]

jobs:

  test-docker-compose:
    name: Publish simpleopcua to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image simpleopcua
        working-directory: ./src/
        run: docker compose up
  
  publish-simpleopcua:
    name: Publish simpleopcua to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image simpleopcua
        working-directory: ./src/opcservers
        run: docker build . --file Dockerfile --tag simpleiot-simpleopcua:latest
        
      - name: Build Latest simpleopcua Docker image
        working-directory: ./src/opcservers
        run: docker tag simpleiot-simpleopcua:latest joaoribeiro5039/simpleiot-simpleopcua:latest

      - name: Docker Push Latest simpleopcua
        run: docker push joaoribeiro5039/simpleiot-simpleopcua:latest
  
  publish-dataprocess:
    name: Publish dataprocess to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image simpleopcua
        working-directory: ./src/dataprocess
        run: docker build . --file Dockerfile --tag simpleiot-dataprocess:latest
        
      - name: Build Latest simpleopcua Docker image
        working-directory: ./src/dataprocess
        run: docker tag simpleiot-dataprocess:latest joaoribeiro5039/simpleiot-dataprocess:latest

      - name: Docker Push Latest simpleopcua
        run: docker push joaoribeiro5039/simpleiot-dataprocess:latest
              